In [2]:
import uncertainties
from uncertainties import unumpy as unp
import astropy.units as u
import numpy as np

We want to check the interaction between uncertainties (unumpy) and astropy.units

In [23]:
x = unp.uarray(1 + np.arange(4), np.ones((4)))
xx = unp.uarray(1 + np.arange(4), np.ones((4)))
x

array([1.0+/-1.0, 2.0+/-1.0, 3.0+/-1.0, 4.0+/-1.0], dtype=object)

In [24]:
x**2, x * xx

(array([1.0+/-2.0, 4.0+/-4.0, 9.0+/-6.0, 16.0+/-8.0], dtype=object),
 array([1.0+/-1.4142135623730951, 4.0+/-2.8284271247461903,
        9.0+/-4.242640687119285, 16.0+/-5.656854249492381], dtype=object))

In [25]:
x / x, xx / x

(array([1.0+/-0, 1.0+/-0, 1.0+/-0, 1.0+/-0], dtype=object),
 array([1.0+/-1.4142135623730951, 1.0+/-0.7071067811865476,
        1.0+/-0.4714045207910317, 1.0+/-0.3535533905932738], dtype=object))

In [26]:
y = x * (1.0 * u.cm)
yy = xx * (1.0 * u.cm)

In [27]:
y, yy

(<Quantity [1.0+/-1.0, 2.0+/-1.0, 3.0+/-1.0, 4.0+/-1.0] cm>,
 <Quantity [1.0+/-1.0, 2.0+/-1.0, 3.0+/-1.0, 4.0+/-1.0] cm>)

In [28]:
y**2, y * yy

(<Quantity [1.0+/-2.0, 4.0+/-4.0, 9.0+/-6.0, 16.0+/-8.0] cm2>,
 <Quantity [1.0+/-1.4142135623730951, 4.0+/-2.8284271247461903,
            9.0+/-4.242640687119285, 16.0+/-5.656854249492381] cm2>)

In [29]:
y / y, yy / y

(<Quantity [1.0+/-0, 1.0+/-0, 1.0+/-0, 1.0+/-0]>,
 <Quantity [1.0+/-1.4142135623730951, 1.0+/-0.7071067811865476,
            1.0+/-0.4714045207910317, 1.0+/-0.3535533905932738]>)

In [30]:
z = y * yy

In [37]:
uncertainties.correlation_matrix([y.value[3], z.value[3]])

array([[1.        , 0.70710678],
       [0.70710678, 1.        ]])

In [31]:
unp.nominal_values(z.value), unp.std_devs(z.value)

(array([ 1.,  4.,  9., 16.]),
 array([1.41421356, 2.82842712, 4.24264069, 5.65685425]))

Test with functions

In [41]:
xxx = unp.degrees(unp.arctan(x))

In [42]:
xxx

array([45.0+/-28.64788975654116, 63.43494882292202+/-11.459155902616466,
       71.56505117707799+/-5.729577951308233,
       75.96375653207353+/-3.3703399713577835], dtype=object)

In [43]:
xxx = unp.degrees(unp.arctan(y.value))

In [44]:
y.value

array([1.0+/-1.0, 2.0+/-1.0, 3.0+/-1.0, 4.0+/-1.0], dtype=object)

In [47]:
unp.nominal_values(xxx)

array([45.        , 63.43494882, 71.56505118, 75.96375653])