In [1]:
from sympy.solvers import solve
from sympy import Symbol
from math import pi,e
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import numpy as np

from scipy.optimize import fsolve

def func(x):

    return ((1+x**2)/2)*(e**((1-x**2)/2))-1/4

root = fsolve(func, 1.5)

root


array([2.52690899])

In [3]:
P_P_0 = [i+2 for i in range(14)]

Roots = []

for i in P_P_0:
    def func(x):

        return ((1+x**2)/2)*(e**((1-x**2)/2))-1/(i)
    
    root = fsolve(func, 1.5)

    Roots.append(root)
    
alpha=2
    
R_R_0 = [i**(-1/alpha)*e**((i**2-1)/(2*alpha)) for i in Roots]
    
import pandas as pd

T = pd.DataFrame(data = [[1/P_P_0[i],Roots[i],R_R_0[i]] for i in range(len(P_P_0))],
                columns = ['P/P_0','M_1', 'R/R_0'])

T

T2 = pd.DataFrame(data = [[1/P_P_0[i],Roots[i],(Roots[i])**2,3/(4*(Roots[i]**2))] for i in range(len(P_P_0))],
                columns = ['P/P_0','M_1', '\rho_2/\rho_1','h/r_1'])
T2

P/P_0                   M_1        \rho_2/\rho_1                  h/r_1
0   0.500000  [2.0872695034502167]  [4.356693980033314]  [0.17214888248686797]
1   0.333333  [2.3618981411410918]  [5.578562829125745]  [0.13444322901307856]
2   0.250000  [2.5269089927774195]  [6.385269057779393]    [0.117457853884207]
3   0.200000   [2.643599193146395]   [6.98861669400427]  [0.10731737521725093]
4   0.166667   [2.733198469715219]  [7.470373874853615]  [0.10039658155860326]
5   0.142857  [2.8055534914820472]  [7.871130393567106]  [0.09528491620631234]
6   0.125000  [2.8660158884661424]  [8.214047072940371]  [0.09130700047613965]
7   0.111111   [2.917807287745739]  [8.513599368422145]  [0.08809434970381981]
8   0.100000  [2.9630120384053216]  [8.779440339734858]  [0.08542685763300605]
9   0.090909  [3.0030532411044946]   [9.01832876890821]  [0.08316396742883411]
10  0.083333  [3.0389440079280536]  [9.235180683321822]  [0.08121118857527657]
11  0.076923  [3.0714301227600624]  [9.433682998997892]  [0.07950235343711146]
12  0.071429  [3.1010758409032033]   [9.61667137103351]  [0.07798956323485108]
13  0.066667   [3.128317957368406]  [9.786373242393635]   [0.0766371751233717]

In [4]:
P_P_0_1 = [i+2 for i in range(14)]
Extr=[1/0.9,1/0.8,1/0.7,1/0.6]
P_P_0=Extr+P_P_0_1

Roots = []

for i in P_P_0:
    def func(x):

        return ((1+x**2)/2)*(e**((1-x**2)/2))-1/(i)
    
    root = fsolve(func, 1.5)

    Roots.append(root)
    
alpha=2
    
h_R_0 = [(i**(-1/alpha))*(3/(4*i**2))*e**((i**2-1)/(2*alpha)) for i in Roots]
rho2_rho0 = [(i**2)*e**((1-i**2)/2) for i in Roots]

T3 = pd.DataFrame(data = [[1/P_P_0[i],Roots[i],rho2_rho0[i],h_R_0[i]] for i in range(len(P_P_0))],
                columns = ['P/P_0','M_1', '\rho_2/\rho_0','h/r_0'])
T3

P/P_0                   M_1          \rho_2/\rho_0  \
0   0.900000    [1.43653166229611]    [1.212460386727212]   
1   0.800000    [1.62750625745831]    [1.161496861145731]   
2   0.700000  [1.7873719314700518]    [1.066245374672153]   
3   0.600000  [1.9372255119437625]   [0.9475195204739406]   
4   0.500000  [2.0872695034502167]   [0.8133176911491646]   
5   0.333333  [2.3618981411410918]    [0.565327410056532]   
6   0.250000  [2.5269089927774195]  [0.43229765955875116]   
7   0.200000   [2.643599193146395]   [0.3499287529591649]   
8   0.166667   [2.733198469715219]   [0.2939804856009608]   
9   0.142857  [2.8055534914820472]  [0.25350708403438516]   
10  0.125000  [2.8660158884661424]   [0.2228675143483692]   
11  0.111111   [2.917807287745739]   [0.1988638471617976]   
12  0.100000  [2.9630120384053216]     [0.17954893193761]   
13  0.090909  [3.0030532411044946]  [0.16366962770180535]   
14  0.083333  [3.0389440079280536]   [0.1503829612956301]   
15  0.076923  [3.0714301227600624]  [0.13910101027020574]   
16  0.071429  [3.1010758409032033]  [0.12940121699633922]   
17  0.066667   [3.128317957368406]  [0.12097205764438175]   

                    h/r_0  
0    [0.3955985401577511]  
1     [0.335172394947937]  
2      [0.30395569363387]  
3   [0.28575702167852984]  
4    [0.2757803777585336]  
5    [0.2748017508441885]  
6    [0.2839784731235524]  
7      [0.29497012544141]  
8    [0.3061225050545589]  
9   [0.31698476038720674]  
10   [0.3274311460311606]  
11   [0.3374414572584375]  
12  [0.34703216241569557]  
13    [0.356231786044611]  
14  [0.36507147422690406]  
15  [0.37358132869251404]  
16  [0.38178907920762556]  
17   [0.3897197345388107]

In [5]:
cocientes=[((i**2)/(i**(1/alpha)))*e**((i**2-1)/(2*alpha)) for i in Roots]
cocientes

[array([2.24623002]),
 array([3.13543388]),
 array([4.1362688]),
 array([5.3660704]),
 array([6.9793698]),
 array([11.40257374]),
 array([15.43769869]),
 array([19.20875477]),
 array([22.77816165]),
 array([26.18492497]),
 array([29.45595445]),
 array([32.61096071]),
 array([35.66499167]),
 array([38.62989542]),
 array([41.51522821]),
 array([44.32884911]),
 array([47.07732619]),
 array([49.76622345])]